<?php

$hobbitFemaleFirstNameSyllables = array("a", "dal", "dri", "da", " ", "al", "fri", "da", " ", "a", "mal", "da", " ", "a", "man", "da", " ", "a", "ra", "bel", "la", " ", "a", "ma", "ran", "th", " ", "ame", "thys", "t", " ", "an", "ge", "li", "ca", " ", "a", "ra", "bel", "la", " ", "as", "pho", "del", " ", "bel", "ba", "be", "lin", "da", "bel", "li", "si", "ma", "bell", " ", "bel", "la", "don", "na", "ber", "tha", "be", "ryl", "la", "ca", "me", "li", "a", "ca", "ra", "ce", "lan", "di", "ne", "ca", "ra", "mel", "la", "ce", "len", "di", "ne", "co", "ra", "cor", "ne", "li", "a", "chi", "ca", "da", "i", "sy", "di", "a", "man", "da", "ro", "sa", "mun", "da", "di", "a", "mon", "d,di", "na", "don", "na", "mi", "ra", "do", "ra", "du", "en", "na", " ", "e", "glan", "ti", "ne", " ", "e", "la", "nor", " ", "es", "me", "ral", "da", " ", "es", "tel", "la", "fa", "ti", "ma", "ger", "da", "gil", "ly", "glo", "ri", "a", "na", "gol", "di", "loc", "ks", "gri", "mal", "da", "hil", "da", "jas", "mi", "ne", "je", "mi", "ma", "jes", "sa", "mi", "ne", "la", "li", "a", "lau", "ra", "la", "vi", "ni", "a", "li", "ly", "lin", "da", "lo", "be", "li", "a", "mal", "va", "ma", "ri", "gol", "d", "man", "tis", "sa", "me", "li", "lot", " ", "ma", "til", "da", "me", "ne", "gil", "da", "ma", "xi", "ma", "ma", "y", "mel", "ba", "me", "li", "lot", " ", "me", "lis", "sa", "me", "ne", "gil", "da", "men", "tha", "mi", "mo", "sa", "mi", "ra", "bel", "la", "mi", "ran", "da", "myr", "tle", "ni", "na", "no", "ra", "pam", "phi", "la", "pim", "per", "nel", " ", "pan", "do", "ra", "pan", "sy", "pe", "ar", "l,pe", "o", "ny", "per", "vin", "ca", "pim", "per", "nel", " ", "pop", "py", "pri", "ma", "prim", "ro", "se", "pri", "mu", "la", "pris", "ca", "re", "gi", "na", "rho", "da", "ro", "bi", "ni", "a", "ro", "sa", "ro", "sa", "mun", "da", "ro", "se", "ro", "wan", " ", "ru", "by", "sal", "vi", "a", "sa", "van", "na", "se", "li", "na", "se", "mo", "li", "na", "do", "ra", "tan", "ta", " ", "y", "o", "lan", "da", " ");



/*
Adaldrida,Alfrida,Amalda,Amanda,Arabella,Amaranth,Amethyst,Angelica,Arabella,Asphodel,Belba,Belinda,Bellisima,Bell,Belladonna,Bertha,Berylla,Camelia,Cara,Celandine,Caramella,Celendine,Cora,Cornelia,Chica,Daisy,Diamanda,Rosamunda,Diamond,Dina,Donnamira,Dora,Duenna,Eglantine,Elanor,Esmeralda,Estella,Fatima,Gerda,Gilly,Gloriana,Goldilocks,Grimalda,Hilda,Jasmine,Jemima,Jessamine,Lalia,Laura,Lavinia,Lily,Linda,Lobelia,Malva,Marigold,Mantissa,Melilot,Matilda,Menegilda,Maxima,May,Melba,Melilot,Melissa,Menegilda,Mentha,Mimosa,Mirabella,Miranda,Myrtle,Nina,Nora,Pamphila,Pimpernel,Pandora,Pansy,Pearl,Peony,Pervinca,Pimpernel,Poppy,Prima,Primrose,Primula,Prisca,Regina,Rhoda,Robinia,Rosa,Rosamunda,Rose,Rowan,Ruby,Salvia,Savanna,Selina,Semolina,Dora,Tanta,Yolanda

http://marello.org/tools/syllabifier/

*/

?>